name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:Hey Welcome to My BloodBank Repository
    runs-on:[self-hosted, linux, x64, gpu]
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"
